'use client';

import { VideoJob } from '@/types';
import { X, Loader2, Clock, AlertCircle, Sparkles } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Badge } from '@/components/ui/badge';

interface ProcessingModalProps {
  job: VideoJob | null;
  isOpen: boolean;
  onClose: () => void;
}

export function ProcessingModal({ job, isOpen, onClose }: ProcessingModalProps) {
  if (!job) return null;

  const getDisplayProgress = () => {
    if (job.status === 'pending') return 10;
    if (job.status === 'post-processing') return 90;
    if (job.status === 'processing') return Math.max(20, Math.min(85, job.progress || 0));
    return job.progress || 0;
  };

  const getStatusBadge = () => {
    switch (job.status) {
      case 'pending':
        return <Badge className="bg-yellow-500/10 text-yellow-500">In Queue</Badge>;
      case 'processing':
        return <Badge className="bg-blue-500/10 text-blue-500">Processing</Badge>;
      case 'post-processing':
        return <Badge className="bg-purple-500/10 text-purple-500">Post-Processing</Badge>;
      case 'failed':
        return <Badge className="bg-red-500/10 text-red-500">Failed</Badge>;
      default:
        return <Badge className="bg-green-500/10 text-green-500">Complete</Badge>;
    }
  };

  const getStatusMessage = () => {
    switch (job.status) {
      case 'pending':
        return 'Your video is in the queue and will start processing soon.';
      case 'processing':
        return 'Your video is being generated by AI. This may take 1-5 minutes.';
      case 'post-processing':
        return 'Almost done! Adding final touches to your video.';
      case 'failed':
        return job.error || 'Something went wrong. Please try again.';
      default:
        return 'Your video is ready!';
    }
  };

  const formatModelName = (model: string) => {
    const modelNames: Record<string, string> = {
      sora2: 'SORA 2',
      veo3: 'VEO 3',
      grok: 'GROK',
      wan26: 'WAN 2.6',
      seedance: 'SEEDANCE',
      kling26: 'KLING 2.6',
    };
    return modelNames[model] || model.toUpperCase();
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            {job.status === 'failed' ? (
              <AlertCircle className="w-5 h-5 text-red-500" />
            ) : (
              <Sparkles className="w-5 h-5 text-primary" />
            )}
            Video Processing
          </DialogTitle>
        </DialogHeader>

        <div className="flex flex-col items-center py-6">
          {/* Large animated progress circle */}
          {job.status !== 'failed' && job.status !== 'complete' && (
            <div className="relative w-32 h-32 mb-6">
              {/* Background circle */}
              <div className="absolute inset-0 rounded-full border-4 border-muted" />

              {/* Progress ring */}
              <svg className="absolute inset-0 w-full h-full -rotate-90">
                <circle
                  cx="64"
                  cy="64"
                  r="60"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="4"
                  className="text-primary"
                  strokeDasharray={`${getDisplayProgress() * 3.77} 377`}
                  strokeLinecap="round"
                />
              </svg>

              {/* Rotating ring animation */}
              <div
                className="absolute inset-2 rounded-full border-2 border-transparent border-t-primary/50 animate-spin"
                style={{ animationDuration: '2s' }}
              />

              {/* Center content */}
              <div className="absolute inset-4 rounded-full bg-card flex flex-col items-center justify-center">
                <span className="text-3xl font-bold">{getDisplayProgress()}%</span>
              </div>
            </div>
          )}

          {/* Failed icon */}
          {job.status === 'failed' && (
            <div className="w-32 h-32 rounded-full bg-red-500/10 flex items-center justify-center mb-6">
              <AlertCircle className="w-16 h-16 text-red-500" />
            </div>
          )}

          {/* Status badge */}
          <div className="mb-4">{getStatusBadge()}</div>

          {/* Status message */}
          <p className="text-center text-muted-foreground mb-6">
            {getStatusMessage()}
          </p>

          {/* Video details */}
          <div className="w-full space-y-3 bg-muted/50 rounded-lg p-4">
            <div className="flex items-start gap-2">
              <Sparkles className="w-4 h-4 text-primary mt-0.5 shrink-0" />
              <div>
                <p className="text-xs text-muted-foreground">Model</p>
                <p className="text-sm font-medium">{formatModelName(job.model)}</p>
              </div>
            </div>

            <div className="flex items-start gap-2">
              <Clock className="w-4 h-4 text-primary mt-0.5 shrink-0" />
              <div>
                <p className="text-xs text-muted-foreground">Prompt</p>
                <p className="text-sm line-clamp-3">{job.prompt}</p>
              </div>
            </div>
          </div>

          {/* Tips */}
          {job.status !== 'failed' && job.status !== 'complete' && (
            <div className="mt-6 text-xs text-muted-foreground text-center space-y-1">
              <p>This usually takes 1-5 minutes depending on the model.</p>
              <p>You can close this and come back later.</p>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
